model_list:
  - model_name: gpt-4o-mini
    litellm_params:
      model: gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4-turbo
    litellm_params:
      model: gpt-4-turbo
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4
    litellm_params:
      model: gpt-4
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY
  - model_name: claude-3-opus
    litellm_params:
      model: claude-3-opus
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-3-sonnet
    litellm_params:
      model: claude-3-sonnet
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-3-haiku
    litellm_params:
      model: claude-3-haiku
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: command-r
    litellm_params:
      model: command-r
      api_key: os.environ/COHERE_API_KEY
  - model_name: command-r-plus
    litellm_params:
      model: command-r-plus
      api_key: os.environ/COHERE_API_KEY
  - model_name: mistral-medium
    litellm_params:
      model: mistral/mistral-medium
      api_key: os.environ/MISTRAL_API_KEY
  - model_name: mistral-small
    litellm_params:
      model: mistral/mistral-small
      api_key: os.environ/MISTRAL_API_KEY
  - model_name: gemini-pro
    litellm_params:
      model: gemini/gemini-pro
      api_key: os.environ/GEMINI_API_KEY
  - model_name: gemini-ultra
    litellm_params:
      model: gemini/gemini-ultra
      api_key: os.environ/GEMINI_API_KEY

litellm_settings:
  drop_params: true
  fallbacks: [
    {
      "openai/gpt-4": ["openai/gpt-3.5-turbo", "anthropic/claude-3-sonnet"],
      "anthropic/claude-3-opus": ["anthropic/claude-3-sonnet", "openai/gpt-4"]
    }
  ]
